### ISSUE TITLE
Invalid or unsupported rule

### ISSUE THREAD

**Issue by chervaliery** [clem9669/hashcat-rule#2]
Hello,

I try to use your rules but got the following errors:

For `clem9669_small.rule`
```
Skipping invalid or unsupported rule in file clem9669_small.rule on line 113: $€
Skipping invalid or unsupported rule in file clem9669_small.rule on line 225: ^€
``` 
For `clem9669_medium.rule`
``` 
Skipping invalid or unsupported rule in file clem9669_medium.rule on line 18835: $€
Skipping invalid or unsupported rule in file clem9669_medium.rule on line 20461: ^€
Skipping invalid or unsupported rule in file clem9669_medium.rule on line 36665: c $€
Skipping invalid or unsupported rule in file clem9669_medium.rule on line 36666: c ^€
Skipping invalid or unsupported rule in file clem9669_medium.rule on line 41417: u $€
Skipping invalid or unsupported rule in file clem9669_medium.rule on line 41418: u ^€
``` 

I skip the `clem9669_medium.rule` as there is 147 276 errors, but here the list: [error_large.log](https://github.com/clem9669/hashcat-rule/files/6597231/error_large.log)

My hashcat version:
```
$ hashcat --version   
v6.1.1
```
It  stills work of the others, but have you any idea why these errors occurred ?

Thanks for your work !

**Comment by clem9669** [comment]
Hello @chervaliery, 

**Thanks for helping out by using the rules.**

I have the exact same error output as you.

I am investigating what could be the root cause. I guess the € symbol is not correctly supported by hashcat.
However, I have discovered thanks to you several unexpected errors in *clem9669_large.rule*.

I will do the necessary and push 😉

**Comment by clem9669** [comment]
Re @chervaliery,

Turns out that hashcat do not support ASCII extended characters. So It is not possible to have rules as $µ or ^€ 😕 
I have reverted my previous commit where I added those. 

I guess a password containing a ASCII extended characters is safe from hashcat. (e.g. MonPassword€) 😄 
I have raised an issue in hashcat repo, but I doubt, there will be a follow-up. 🤷‍♂️
